version: 2
updates:
  # Enable version updates for npm (used by bun)
  - package-ecosystem: 'npm'
    directory: '/' # Location of package manifests
    schedule:
      interval: 'weekly'
    # Raise pull requests for version updates
    # to npm against the `main` branch
    target-branch: 'main'
    # Labels to add to the pull requests
    labels:
      - 'dependencies'
    # Group patch and minor updates into a single PR
    groups:
      npm-patch-and-minor:
        dependency-type: 'direct'
        update-types:
          - 'patch'
          - 'minor'

  # Enable version updates for GitHub Actions
  - package-ecosystem: 'github-actions'
    directory: '/'
    schedule:
      interval: 'weekly'
    target-branch: 'main'
    labels:
      - 'github-actions'
      - 'dependencies'
